#!/bin/bash

# uclibc-toolchain-link

# Copyright (C) 2016 Ingenic Semiconductor CO.,LTD.
# Cheng Lulu <lulu.cheng@ingenic.com>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, see the file COPYING, or write
# to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

prefix="mips-linux-uclibc-gnu"

for tool in `ls .`
do
    postfix=${tool##*mips-linux-gnu-}
    if [[ $tool =~ mips-linux-gnu ]];then
	case "${postfix}" in
	    go|gofmt|gccgo)
		;;
	    *cc|*cc-[0-9]*|*++|*cpp|*fortran)
		ln -sf uclibc-toolchain-wrapper $prefix-$postfix;
		;;
	    *)
		ln -sf $tool $prefix-$postfix
		;;
	esac;
    fi
done
