#!/bin/bash

_generate_outside_dejagnu_exps()
{
    local _project=$1
    local _sub_project=$_project

    if [ "$2"x != ""x ];then
	_sub_project=$2
    fi

    run_dir="${dejagnu_dir}/${_sub_project}"
    out_dir="${dejagnu_dir}/${_sub_project}/out/${time_stamp}"
    obj_dir="${install_path}/${toolchain_target}/bin/./"

    export run_dir src_dir out_dir obj_dir tool tool_exec

    mkdir -p ${run_dir}
    mkdir -p ${out_dir}

    local sshcpfile="${dejagnu_dir}/sshcp.exp"
    local sitefile="${dejagnu_dir}/site.exp"
    local runtestfile="${dejagnu_dir}/runtest.sh"
    local sde_elf_standard="${dejagnu_dir}/standard.exp"

    sh ${work_path}/dejagnu/site.sh    $_project > ${sitefile}
    sh ${work_path}/dejagnu/sshcp.sh   $_project > ${sshcpfile}
    if [ "$toolchain_target"x = "mips-sde-elf"x ];then
	cat ${work_path}/dejagnu/mips-idt.exp > ${sshcpfile}
	cat ${work_path}/dejagnu/standard.exp > ${sde_elf_standard}
    fi
    sh ${work_path}/dejagnu/runtest.sh "outside" > ${runtestfile}

    sed -i -f ${work_path}/dejagnu/localenv.sed \
	${sitefile} \
	${sshcpfile} \
	${runtestfile}

    check_run "chmod +x ${runtestfile}"
    check_run "cp ${runtestfile} ${run_dir}"
}

_dejagnu_outside_gcc()
{
    if [ "$1"x = ""x ];then
	echo "Error ** _dejagnu_outside_gcc"
	exit 1
    fi
    src_dir=${local_path}/src/`ls ${local_path}/src | grep gcc-[457]-20.*`
    src_dir="${src_dir}/gcc/testsuite"
    tool="$1"
    tool_exec="${toolchain_target}-${tool}"
    if [ "$tool"x = "gccgo"x ];then
	tool="go"
    fi

    _generate_outside_dejagnu_exps gcc $tool

    if [ "$tool"x = "gfortran"x ];then
	echo "# auto generated by gen-outside-dejagnu.sh for" \
	     "gfortran include_6.s" > $out_dir/gfortran.log
    fi
}

_dejagnu_outside_base_run()
{
    local project=$1
    pushd ${run_dir}

    echo "Dejagnu [$run_dir] ... "
    vexe "./runtest.sh"

    mkdir -p ${outputdir}/${project}

    cp -rfda ${out_dir}/* \
       ${outputdir}/${project}

    echo "Dejagnu [$run_dir] finish"

    popd
}

dejagnu_outside_running()
{
    local project=$1
    local case=$2

    export outside=y
    if [ "$project"x = "gcc"x ]; then
	check_run "_dejagnu_outside_gcc gcc"
	check_run "_dejagnu_outside_base_run gcc"

	check_run "_dejagnu_outside_gcc g++"
	check_run "_dejagnu_outside_base_run g++"
	if [ "$toolchain_target"x != "mips-sde-elf"x ];then
	    check_run "_dejagnu_outside_gcc gfortran"
	    check_run "_dejagnu_outside_base_run gfortran"
	    check_run "_dejagnu_outside_gcc gccgo"
	    check_run "_dejagnu_outside_base_run gccgo"
	fi
    else
	echo "*** dejagnu outside env: now only support 'gcc' test. you set '$1'"
	exit 1
    fi
}
