#!/usr/bin/expect
set targetip [lindex $argv 0]
set sshport [lindex $argv 1]
spawn ssh-keygen -f "~/.ssh/known_hosts" -R $targetip
spawn ssh-copy-id "root@$targetip -p $sshport"
expect {
    "*(yes/no)*" { send "yes\n"}
    "* password:" { send "123456\n"}
}

spawn scp -P $sshport /tmp/a root@${targetip}:~
sleep 2

expect {
    "* password:" { exit 1 }
    "*100%*"   { exit 0 }
}

expect  eof
exit
